name: Bug
description: File a bug report.
title: "bug:"
type: "Bug"
projects: ["proculair/3"]

body:
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: Describe the problem you are experiencing. Screenshots are welcome.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: Describe what you expect to happen instead.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Addtional Context
      description: Add any other context about the problem here.
    validations:
      required: false
